### ISSUE TITLE
Literate Haskell support?

### ISSUE THREAD

**Issue by pharpend** [chrisdone/hindent#103]
```haskell
> runTn :: IO ()
> runTn = do
>  args <- getArgs
>  let fstarg = headMay args
>      rstof = tailMay args
>  case fstarg of
>    Nothing -> editToday
>    Just cmd ->
>      case cmd of
>        "edit" ->
>          case rstof of
>            Just (s:_) ->
>              case readMay s of
>                Nothing -> help
>                Just d  -> editEntry d
>            _ -> help
>        _ -> help
>
```

Getting `hindent: Parse error: >` when I run `M-x hindent/reformat-decl` on that function. Does Hindent not have Literate Haskell support?

I'll see if I can reproduce using TeX style

**Comment by mgsloan** [comment]
It doesn't, but it should be easy enough to add something to strip the `> ` when editing a `.lhs`

TeX style should work fine, because `shm` attempts to guess the boundaries of the declaration being edited, and only sends that to `haskell-src-exts`.

**Comment by chrisdone** [comment]
Indeed, TeX style should require no special support.

**Comment by gibiansky** [comment]
It sounds like this should probably be a feature added to the editor scripts, not `hindent` Haskell code itself, yeah?

**Comment by chrisdone** [comment]
I suppose either works. But if TeX style works just fine then we don't have to bother with bird-style. A bunch of tooling doesn't work with bird-style anyhoo.

**Comment by pharpend** [comment]
@gibiansky Well, no, because editors other than vim & emacs might want this functionality. In that case, they'll undoubtedly encounter this bug at some point. It seems like it should be fixed in HIndent so that everyone doesn't have to add their own patch.

**Comment by gibiansky** [comment]
This is supported now that #111 is merged.
