### ISSUE TITLE
Formatting breaks typesignatures with operators.

### ISSUE THREAD

**Issue by adamse** [chrisdone/hindent#107]
Using the master branch of hindent and the `chris-done` style:

Before formatting:
~~~
comp :: Eff (STEFF s :> r) String
~~~
After formatting:
~~~
comp :: Eff (STEFF s (:>) r) String
~~~

Notice how the `:>` is now parenthesised.

**Comment by gibiansky** [comment]
I recently fixed something similar in a slightly different part of the AST [here](https://github.com/chrisdone/hindent/issues/91). Probably the same issue.

**Comment by chrisdone** [comment]
I think this is present in the fundamental style:

    λ> test fundamental "x :: Int (x :> y)"
    x :: Int (x (:>) y)

I think the other styles are probably using that for types. Mine certainly is. Just a case of fixing Pretty.hs, I expect. [Here.](https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L544..L549)

**Comment by chrisdone** [comment]
It's weird, you'd think that `TyInfix` would have a `QOp` in it rather than a `QName`.

**Comment by chrisdone** [comment]
``` haskell
λ> test fundamental "x :: Int (x :> y)"
x :: Int (x :> y)
λ> test chrisDone "x :: Int (x :> y)"
x :: Int (x :> y)
λ> test gibiansky "x :: Int (x :> y)"
x :: Int (x :> y)
```

**Comment by chrisdone** [comment]
Bumped on Hackage as 4.4.1.
