### ISSUE TITLE
Tibbe style: case alt turns into a match

### ISSUE THREAD

**Issue by mboes** [chrisdone/hindent#115]
Consider:
```Haskell
case x of
        _ -> do launchMissiles
```
`hindent` renders the above as
```Haskell
case x of
    _ = do launchMissiles
```
which is syntactically incorrect.

**Comment by chrisdone** [comment]
Ah, this is a regression caused after HSE meddled with their Rhs type. Johan's style has a particular special case for `do` in RHS to implement the "swinging" of children underneath. Should be an easy fix.
