### ISSUE TITLE
Gibiansky style and multi-branch if's

### ISSUE THREAD

**Issue by pharpend** [chrisdone/hindent#118]
Hey, @gibiansky 

On `case` statements, your style aligns the `->`s. That is:

```haskell
case x of
  foo  -> bar
  quux -> baz
```

Shouldn't your style do the same thing with multi-branch `if`s?

```haskell
rdline s = readline s >>= \case                     
             Just x -> if | words x == [] -> Nothing
                          | otherwise -> Just x     
             Nothing -> Nothing                     
```

Notice how the `->`s are not aligned, even though the syntax is similar to `case`.

**Comment by gibiansky** [comment]
Yes, I would align these, to be consistent with `case`.
