### ISSUE TITLE
A few nitpicks with the chris-done style

### ISSUE THREAD

**Issue by pharpend** [chrisdone/hindent#123]
1. Sometimes the line breaks following infix operators are rather superfluous:

```haskell
bounce n
  | n > o = bounce (2 * o - n)
  | n < -o =
    bounce ((-2) *
            o -
            n)
  | otherwise = n
```

I would think something like this would be more consistent with your style:

```haskell
bounce n | n > o     = bounce (2 * o - n)
         | n < -o    = bounce ((-2) * o - n)
         | otherwise = n
```

2. The `$` operator is roughly equivalent to wrapping the rest of the line in parentheses. Shouldn't the style reflect this, instead of treating `$` like an ordinary infix operator?

```haskell
f =
  fooBarBaz $
  xToTheYTo x y z $
  quux quzz fuzzy
```
Maybe something like this?

```haskell
f = fooBarBaz $ xToTheYTo x y z
              $ quux quzz fuzzy
```

I know you hate infix operators, so maybe I should be talking to @gibiansky.

3. When I have a bunch of functions in a row, is there any argument against aligning the `=` signs?

```haskell
gameSize = 300
windowWidth = 800
windowHeight = 600
ballRadius = 2.0e-2
speedIncrease = 1.2
losingAccuracy = 0.9
winningAccuracy = 0.1
initialSpeed = 0.6
paddleWidth = 2.0e-2
paddleHeight = 0.3
paddleSpeed = 1
textSize = 1.0e-3
```

The `=` alignment makes the functions a lot easier to read. I'm at the moment too lazy to align them manually. (This is why I use HIndent).

**Comment by ocharles** [comment]
I personally wouldn't want the automatic alignment stuff, it leads to larger than necessary diffs and makes reviews harder - not to mention imposing a burden on anyone collaborating on the project.
