### ISSUE TITLE
Preserve empty lines when reformatting code

### ISSUE THREAD

**Issue by geraldus** [chrisdone/hindent#124]
When I use `M-q` to reformat code block it is always removes all empty lines within it.

I use empty lines to separate logical code pieces one from another. Current behaviour annoying a bit, because each time I use `hindent-reformat-decl-or-fill` (e.g. after some additions or edits) I have to restore empty lines manually.

Any thoughts?

**Comment by gibiansky** [comment]
What style are you using? Different styles work differently in this regard.

**Comment by geraldus** [comment]
I use Chris Done's style.

**Comment by chrisdone** [comment]
Empty lines aren't part of my style. :3

**Comment by geraldus** [comment]
Well, feel free to close this issue in this case. (: Though will such feature will affect your code is there are no empty lines already?

**Comment by hasufell** [comment]
There are no styles anymore and no apparent way to preserve empty lines. Removing empty lines it not really a trivial suggestion/decision. In fact it's very intrusive.
