### ISSUE TITLE
Tibell style converts = to -> inside case expressions

### ISSUE THREAD

**Issue by johnw42** [chrisdone/hindent#127]
Tibell style turns this...

```Haskell
foo = case 0 of _ -> let x = 42 in x
```

...into this (modulo formatting)...

```Haskell
foo = case 0 of _ -> let x -> 42 in x
```

**Comment by chrisdone** [comment]
That's weird. Damn, HSE really have us paying technical debt over with their Rhs type change, @gibiansky.

**Comment by gibiansky** [comment]
Ugh. Yeah, very frustrating. Should be fixed now.
