### ISSUE TITLE
Error on any hindent command

### ISSUE THREAD

**Issue by wedens** [chrisdone/hindent#128]
Oh every command (hindent-reformat-buffer, hindent-reformat-region etc) I get this error:
```
hindent-decl-points: Invalid function: (jump nil (search-backward-regexp "^[^ 
]" nil t 1) (cond ((save-excursion (goto-char (line-beginning-position)) (looking-at "|]")) (jump)) (t (unless (or (looking-at "^-}$") (looking-at "^{-$")) (point)))))
```
emacs 24.5, latest version of hindent from melpa.

**Comment by banx** [comment]
I get the same error. When compiling I get this message (using emacs 24.3):

> hindent.el:236:1:Warning: the following functions are not known to be defined:
>    flet, jump

**Comment by mitochon** [comment]
I have the same issue. I'm on
GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2015-04-10 on builder10-9.porkrind.org
(via emacsformacosx)

**Comment by filib** [comment]
+1

**Comment by filib** [comment]
@chrisdone happy to help here if you can point us in the right direction in order to debug.

**Comment by chrisdone** [comment]
Oh, probably they just need to be changed to CL-FLET perhaps. Let me look at the code.

**Comment by filib** [comment]
Yeah, I think you're right. It looks like there's a little [jiggery-pokery to get it working correctly](http://endlessparentheses.com/understanding-letf-and-how-it-replaces-flet.html). Would you like me to have a look?

**Comment by filib** [comment]
Took a crack at this one in https://github.com/chrisdone/hindent/pull/154. Took a rather pragmatic approach so happy to look at alternative solutions if you'd like me to.

**Comment by chrisdone** [comment]
What about using cl-letf? Seems like it doesn't incur a new dependency as cl-lib already comes with Emacs.

**Comment by filib** [comment]
Seems like a fair point to me. I'll take a crack at it.

**Comment by filib** [comment]
Got a bit of time this morning and took a crack at it in https://github.com/chrisdone/hindent/pull/159.
