### ISSUE TITLE
hindent mangles code with infix operator

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/hindent#131]
Before
```haskell
test3 :: TestTree
test3 = testCase "test3" $ do
    a
    @?= b
```

After
```haskell
test3 :: TestTree
test3 =
  testCase "test3" $
  do a @?=
  b
```

Tibell and Done break in the same way, Gibiansky doesn't break.

**Comment by chrisdone** [comment]
I think this is probably an operator precedence issue. I think it's parsing it as `(do a) @?= b`. ChrisDone and JohanTibell style print operators line separated with the operator at the end of each line, which would explain this printing. The correct parse would be `do (a @?= b)`, which gives you

``` haskell
test3 = testCase "test3" $ do
    (a
     @?= b)
```

→ 
``` haskell
test3 =
  testCase "test3" $
  do (a @?= b)
```

Gibiansky's style is less aggressive at line breaking operators so it works by coincidence.

Related #50.
