### ISSUE TITLE
Gibiansky style: multiline comments are improperly moved in some cases

### ISSUE THREAD

**Issue by gittywithexcitement** [chrisdone/hindent#136]
Here's an example of where a multiline comment will be moved:

```haskell
data Foo =
       Foo
         { bar :: Integer --this comment is OK
         , baz :: Integer -- this long comment will be truncated. Any lines beyond the first 
                        -- will be moved down. long long long long long long 
         }

qux = 1
```

output:

```haskell
data Foo =
       Foo
         { bar :: Integer --this comment is OK
         , baz :: Integer -- this long comment will be truncated. Any lines beyond the first
         }

                 -- will be moved down. long long long long long long
qux = 1
```

using latest commit: 726c692d234581c853495165472c78f4c7fb9297

**Comment by gibiansky** [comment]
What version of `hindent` and what arguments are you passing to it? I'm not observing this on 4.5.3 or 4.4.2...

**Comment by gittywithexcitement** [comment]
Sorry, my example was incomplete. Please see the updated example.

**Comment by gittywithexcitement** [comment]
@gibiansky did you see my update?

**Comment by gibiansky** [comment]
I did, but sadly at the moment I don't have time to work on this. Putting some effort into `hindent` and especially the comment localization is on my todo list. Although it does feel like this is replicating the work of `ghc-exactprint` to some extent.

**Comment by gittywithexcitement** [comment]
Understood :smile: 

I was wondering how hindent 'fits in' with ghc-exactprint (obviously they have somewhat different purposes).

**Comment by gibiansky** [comment]
`hindent` was created way before the GHC changes that made `ghc-exactprint` happen were feasible. If the GHC API were easy to work with (as easy as `haskell-src-exts`) `hindent` may have been written with the GHC API instead. Even now it is hard to tell how mature that is – probably not yet mature enough to try to migrate `hindent` to GHC API / `ghc-exactprint`. That *may* be worthwhile in the long term (hard to say), but it would be a lot of work, so may never happen.
