### ISSUE TITLE
chris-done style too aggressive with line breaks

### ISSUE THREAD

**Issue by pharpend** [chrisdone/hindent#143]
Hello, @chrisdone .

Your style guide specifies 80 character lines, with exceptions for things like long strings. Yet, HIndent will reformat this:

```haskell
-- |Take a 'BotConf' and turn it into a 'BotState'. The only exception
-- this might throw is if 'bcNicks' returns '[]'.
fromBotConf :: BotConf -> Exceptional BotState
fromBotConf cfg =
  do nick <- case bcNicks cfg of
              [] -> fail "Nicks list mustn't be empty!"
              (x:_) -> pure x
     return (BotState {botNick = T.unpack nick
                      ,botSource = T.unpack (bcSourceUrl cfg)
                      ,botBugs = T.unpack (bcBugsUrl cfg)
                      ,botManual = T.unpack (bcManualUrl cfg)
                      ,botPrefix = T.unpack (bcPrefix cfg)})
```

into:

```haskell
-- |Take a 'BotConf' and turn it into a 'BotState'. The only exception
-- this might throw is if 'bcNicks' returns '[]'.
fromBotConf :: BotConf -> Exceptional BotState
fromBotConf cfg =
  do nick <-
       case bcNicks cfg of
         [] ->
           fail "Nicks list mustn't be empty!"
         (x:_) -> pure x
     return (BotState {botNick = T.unpack nick
                      ,botSource =
                         T.unpack (bcSourceUrl cfg)
                      ,botBugs =
                         T.unpack (bcBugsUrl cfg)
                      ,botManual =
                         T.unpack (bcManualUrl cfg)
                      ,botPrefix =
                         T.unpack (bcPrefix cfg)})
```

The first is a bit more readable, and, correct me if I'm wrong, 100% compliant with your style.

Thank you!

**Comment by adamse** [comment]
I too have experienced this! Although this might be intended see https://github.com/chrisdone/hindent/blob/master/src/HIndent/Styles/ChrisDone.hs#L35

**Comment by chrisdone** [comment]
This was an intentional heuristic as it probably suited the general case better, but I can't remember exactly which cases. I've changed it to only be based on the column. Let's try this out for a bit before I push to hackage.

**Comment by pharpend** [comment]
@chrisdone FWIW, I got decent behavior by just changing the `50` in @adamse's file to `80`.

(I recognize that you wrote the file, not @adamse, I was just using his name to refer to the link he posted).
