### ISSUE TITLE
hindent cannot read files from command-line arguments or emacs hindent-reformat-buffer

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/hindent#161]
`hindent --style fundamental Fundamental.hs` gets stuck.

File is: https://github.com/chrisdone/hindent/blob/master/src/HIndent/Styles/Fundamental.hs

**Comment by gibiansky** [comment]
Thanks! This is definitely a bug and should be fixed, but just FYI the `fundamental` style isn't really meant to be used directly, but only as a base for other styles. (You may want to use `chris-done` or `gibiansky` or some of the other styles.)

**Comment by bitemyapp** [comment]
@gibiansky I knew that, this was to accentuate the oddness that it was failing.

It also gets stuck on gibiansky,

**Comment by gibiansky** [comment]
Ah, I bet this is crappy documentation. You should run it as
```bash
cat Fundamenta.hs | hindent --style gibiansky
```

Passing files as an argument just waits for input from `stdin`. 

This has actually confused at least one or two people in the past, so it *clearly* needs to be fixed.

**Comment by bitemyapp** [comment]
@gibiansky it gets stuck when I run "hindent-reformat-buffer" on that file as well in Emacs.

**Comment by gibiansky** [comment]
Hmm... in that case I'm lost. I'm running it with both `fundamental` and `gibiansky` and it's working fine from the command line. Does it work for you from command-line? (I have never used it in Emacs, I mostly stick to Vim.)

**Comment by bitemyapp** [comment]
@gibiansky piping from the command does indeed work, yes, but I'm using the latest elisp for hindent and Emacs gets stuck invoking hindent.

**Comment by gibiansky** [comment]
Alright, good to know. Sorry I can't help then.

@chrisdone You probably want to chime in here, since you know the Emacs implementation.

**Comment by bitemyapp** [comment]
@gibiansky one other note, I noticed the output of hindent didn't include a terminal newline, any idea what's going on there?

```
    , styleCommentPreprocessor = return
    }%
```

**Comment by gibiansky** [comment]
Agreed, this should be fixed. See #162, I'll get around to it tonight or this weekend if I can.

**Comment by bitemyapp** [comment]
@gibiansky the impression I'm getting is that devs for hindent don't use it to reformat whole files very frequently? Just regions? Do I have that right?

Because what I want is something like go fmt where I can fire-and-forget against whole files at a time.

**Comment by bitemyapp** [comment]
Seems like most people don't use hindent to reformat whole files generally?

My use pattern would be like `go fmt` where I'm fire-and-forgetting at an entire file at a time, but that doesn't seem like the widely used pattern for hindent.

**Comment by gibiansky** [comment]
@bitemyapp I use to reformat regions at a time, but I also use it to verify formatting for whole files. (I run a script that checks that the formatting of a file matches the formatting generated by hindent, and warns me if that is false.)

It needs a bit of performance tuning to really work on large files; on one or two files in the IHaskell codebase it takes 2-3 seconds to reformat. Also, when there is a syntax error, it doesn't really report it in any nice way, and just replaces your entire file with an error message... (at least that's how it works for me in Vim)

I don't know how most other people use it though.

**Comment by gibiansky** [comment]
That said the use case you're mentioning is one we want to support. (`hindent` aims to be the `go fmt` for Haskell. It turns out it's not that simple to build that for a language as complex and varied as Haskell, and there's still more work to do... but we're trying :) )

**Comment by chrisdone** [comment]
Closing this issue (addresses a few issues) in favor of #162, #163, and #164.
