### ISSUE TITLE
hindent should emit trailing newline

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/hindent#162]
Raised [here](https://github.com/chrisdone/hindent/issues/161#issuecomment-156198981) but also I have found this quite annoying in the past and had to work around it repeatedly.

**Comment by chrisdone** [comment]
There's a subtlety here which is to ensure that you only add a newline at the end of a module. By comparison when reformatting a declaration/region in the editor, you don't need an unnecessary newline inserted in the output.

**Comment by chrisdone** [comment]
hindent now emits a newline when specifying a filename as in #163. How's that?
