### ISSUE TITLE
Make hindent-reformat-buffer just send the whole file

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/hindent#164]
At the moment it formats declaration by declaration in a loop, probably that loop is flawed. Now that hindent accepts whole files, it's probably also completely unnecessary to do this process.

Pinging @bitemyapp.

**Comment by bitemyapp** [comment]
@chrisdone give it a spin soon, thank you!

**Comment by bitemyapp** [comment]
It "worked" (took a couple seconds), but the file changed into this:
![screenshot from 2015-11-13 15 25 45](https://cloud.githubusercontent.com/assets/320177/11158023/e4109652-8a1a-11e5-9343-118cbbec3a21.png)

There aren't any newlines between anything.
