### ISSUE TITLE
hindent-reformat-buffer doesn't newline separate declarations

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/hindent#165]
Cf. https://github.com/chrisdone/hindent/issues/164#issuecomment-156560656

**Comment by chrisdone** [comment]
What version of hindent are you testing on? 4.5.6 outputs [two newlines between each declaration.](https://github.com/chrisdone/hindent/blob/1471c3d927e49488aca766ce62e118c7bd62171b/src/HIndent/Pretty.hs#L1197-L1209)
