### ISSUE TITLE
Incorrect formatting on newtype with lots of crazy type level nonsense

### ISSUE THREAD

**Issue by ocharles** [chrisdone/hindent#168]
The following:

```haskell
newtype Attr (f :: TyFun k * -> *) (attr :: k) =
  Attr {unAttr :: Apply f attr}
```

is getting formatted in to

```haskell
newtype Attr (f :: TyFun (k (* -> *))) (attr :: k) =
  Attr {unAttr :: Apply f attr}
```

But that is not the same as what I typed! :)

**Comment by gibiansky** [comment]
What style is this with?

**Comment by chrisdone** [comment]
I'll take a look at this tomorrow. This is rather weird, I'm not sure whether HSE is parsing it correctly or whether the printer is confused.

**Comment by ocharles** [comment]
@gibiansky `chris-done`

**Comment by chrisdone** [comment]
I think this was an HSE bug: https://github.com/haskell-suite/haskell-src-exts/issues/202 I tested out this example on HSE 1.17 and it works properly.
