### ISSUE TITLE
Type equality is broken

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/hindent#177]
Old, known good

```haskell
type DBVal val =
  ( PersistEntity val
  , PersistEntityBackend val ~ SqlBackend
  , PersistStore (PersistEntityBackend val))
```

After hindent chris-done

```haskell
type DBVal val = (PersistEntity val,PersistEntityBackend val == SqlBackend,PersistStore (PersistEntityBackend val))
```

Gets error:

```haskell
        Illegal operator ‘==’ in type ‘PersistEntityBackend val
                                       == SqlBackend’
          Use TypeOperators to allow operators in types
```

Johan Tibell's does this:

```haskell
type DBVal val = (PersistEntity val, PersistEntityBackend val == SqlBackend, PersistStore (PersistEntityBackend val))
```

Gibiansky's crashes and lags my computer.

```
^C^Czsh: killed     hindent --style gibiansky thoth/src/Betterteam/DB.hs
```

Fundamental makes the same error

```haskell
type DBVal val = (PersistEntity val,PersistEntityBackend val == SqlBackend,PersistStore (PersistEntityBackend val))
```

So what's happening?

**Comment by mgsloan** [comment]
Looks like someone thought that `TyEquals` pretty prints as `==` and not `~`.

Maybe it'd be good to have some round-tripping quickcheck tests?

**Comment by bitemyapp** [comment]
@mgsloan type-level Eq does sound pretty funny though

**Comment by mgsloan** [comment]
Funnily enough, a type family does exist for `==`, but it returns the `Bool` kind, not `Constraint`.  https://hackage.haskell.org/package/base-4.8.2.0/docs/Data-Type-Equality.html

**Comment by chrisdone** [comment]
Cheers for the PR. I also pushed a tweak to the long-standing mild annoyance of type tuples, so now in my style it's:

``` haskell
type DBVal val = 
  (PersistEntity val
  ,PersistEntityBackend val ~ SqlBackend
  ,PersistStore (PersistEntityBackend val))
```

**Comment by chrisdone** [comment]
> Maybe it'd be good to have some round-tripping quickcheck tests?

I'd need to improve my QuickCheck-fu to testing recursive data structures but such a test (e.g. for each syntax type) would be great.

**Comment by mgsloan** [comment]
Hmm, I could have sworn there was some TH / generics for generating Arbitrary instances, but I haven't found it.

This may actually be a great application for [smallcheck](https://hackage.haskell.org/package/smallcheck), to exhaustively check small expressions.  Looks like you can use ghc generics, and define an instance for all the types in HSE.  For real concision here, consider th-reify-many :)

Could maybe have the instance for  `Name` be either a really short name or really long, to test expressions getting wrapped.  The capitalization of names would also need to work out... To handle the case where the names are wrong, could just check that (parse (serialize x)) works, before testing that (parse x == parse (hindent x)).
