### ISSUE TITLE
List comprehension and QuasiQuotes

### ISSUE THREAD

**Issue by gracjan** [chrisdone/hindent#180]
When QuasiQuotes are enabled list comprehension may cause parsing error:

```
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> :set -XQuasiQuotes 
Prelude> let x = [ v | v <- [1,2,3]]
Prelude> let x = [v| v <- [1,2,3]]
<interactive>:4:12: unterminated quasiquotation at end of input
Prelude> 
```

The ambiguity is documented in [GHC ticket 11679](https://ghc.haskell.org/trac/ghc/ticket/11679).

Running hindent on TemplateHaskell heavy code like Yesod triggers this problem. Workaround seems to be to add a space before or after the list comprehension variable.

**Comment by chrisdone** [comment]
Indeed, having to add a space is a bit annoying. It's the same for structured-haskell-mode. But at least it's a workaround.
