### ISSUE TITLE
Gibiansky style is too eager with line breaks

### ISSUE THREAD

**Issue by expipiplus1** [chrisdone/hindent#183]
``` haskell
foo :: ()
foo =
  let bar =
             case () of
               _ -> ()
  in ()
```

The line break before the case expression is a little superfluous seeing as the case is indented further than the `=`.

This was formatted with a column width of 80 characters. (The let expression could easily do without the line break before it too)

**Comment by chrisdone** [comment]
I'm taking hindent in a new direction of a single style, closing this issue.

**Comment by expipiplus1** [comment]
Does this issue manifest itself with the new 'single style'?

**Comment by chrisdone** [comment]
Nah, that issue is a gibansky-specific oddity.

**Comment by expipiplus1** [comment]
ok, thanks.
