### ISSUE TITLE
johan-tibell style add extra parenthesis for deriving

### ISSUE THREAD

**Issue by FrancisMurillo** [chrisdone/hindent#185]
Great work with this project :+1: 

Anyhow, given this simple data type
```haskell
data X = X String
               deriving (Show)
```

Formatting it yields an extra parenthesis around (Show)
```haskell
data X = X String
               deriving ((Show))
```

**Comment by chrisdone** [comment]
This was fixed by https://github.com/chrisdone/hindent/pull/197.
