### ISSUE TITLE
Comments are removed from declaration

### ISSUE THREAD

**Issue by cocreature** [chrisdone/hindent#186]
When running hindent on the following
```
trans One e n =
  M.singleton
    (Query Unmarked (Mark NonExistent)) -- The goal of this is to fail always
    (emptyImage {notPresent =
                   S.singleton
                     (TransitionResult Two
                                       (Just A)
                                       n)})
```
using either chris-done, fundamental or johan-tibell style the comment is removed.
I’m using hindent build from master at commit 546025b34a259ea4556505feee301462ac0e9def.

**Comment by chrisdone** [comment]
Thanks for the report. It's about time we fixed this comment insertion business. It's a royal buggerance for relying on hindent.

**Comment by chrisdone** [comment]
Fixed, I rewrote command handling entirely.
