### ISSUE TITLE
Tell hindent to not format imports?

### ISSUE THREAD

**Issue by joe9** [chrisdone/hindent#200]
Hello,

Thanks for providing hindent.

I use both hindent and stylish-haskelll to format the haskell file. I like the way stylish-haskell formats the imports by not merging different groups of imports. hindent tends to merge them into one big group of imports and then format them. I could separate the groups of imports by adding a line of "--" to separate the groups of imports.

Just want to check if there is a way to tell hindent to ignore the imports.

Thanks

**Comment by chrisdone** [comment]
I think rather that hindent could pay attention to newlines between imports. And preserve them.
