### ISSUE TITLE
Expose hindent via intero UX and flycheck

### ISSUE THREAD

**Issue by tonyday567** [chrisdone/hindent#201]
In the spirit of a conversation long ago on #74, style suggestions work best in chunks.  A natural UX then, might be interfacing via flycheck, and being able to apply style suggestions using the intero UX.

As an extra checker, hindent could then rely on a robust workflow to report a warning (eg 'whitespace', 'splitting long line') and the description of the edit, as part of the overall editing flow rather than as a separate process.

The compiler/suggestion list/apply suggestion in intero looks ideal for this.  The bonus would be independence between intero and hindent (and hlint as hlint-refactor is another checker).

**Comment by chrisdone** [comment]
Agreed. I do intend on getting some integration of hindent (and automatic installation, a la hoogle and intero) into intero. I'll come back to this discussion with more feedback later.

**Comment by chrisdone** [comment]
Moving this to the intero repo, as there needs to be work to get hindent integrated with intero first.
