### ISSUE TITLE
Tags for 5.4.2 and 5.4.3 still present, still interfere with melpa-stable

### ISSUE THREAD

**Issue by mdorman** [chrisdone/hindent#202]
Though there are new, lovely tags for 4.5.2 and 4.5.3 (yay!), the tags for [5.4.2](https://github.com/chrisdone/hindent/releases/tag/5.4.2) and [5.4.3](https://github.com/chrisdone/hindent/releases/tag/5.4.3) are still in the repo, and thus still skew melpa-stable.

**Comment by chrisdone** [comment]
Deleted!

**Comment by mdorman** [comment]
Lovely, thank you!
