### ISSUE TITLE
inaccurate version bounds in .cabal file

### ISSUE THREAD

**Issue by hvr** [chrisdone/hindent#203]
haskell-src-exts-1.18 made some backward-incompatible changes (c.f. haskell-infra/hackage-trustees#73)

So now all releases `hindent` starting with version 4.5.7 (which started leaving out the upper bound on HSE) are now broken and require retrofitting a `haskell-src-exts < 1.18` upper bound.

![untitled](https://cloud.githubusercontent.com/assets/285533/17581607/1555a7f4-5fa7-11e6-8c52-a93d9140d6a3.png)

**Comment by hvr** [comment]
@chrisdone This is quite ironic... I just had to put back in the very PVP-mandated upper bound you stopped providing (starting with version 4.5.7). Consequently, leaving off the upper bounds had no benefit whatsoever; to the contrary, leaving them off caused regressions on Hackage for a couple of days, and required the overhead of investigating this, and adding `.cabal` to the index tarball. 

Why did you drop the bounds in the first place?

**Comment by chrisdone** [comment]
Looks like you've already solved your problem. 👍
