### ISSUE TITLE
Trouble with formatting export list

### ISSUE THREAD

**Issue by sighingnow** [chrisdone/hindent#206]
The newest version of hindent (5.0.0) doesn't formatting export list as described in the Johan Tibell haskell style guide [https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#export-lists](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#export-lists)

**Comment by chrisdone** [comment]
Cheers, I'll take a look today.

**Comment by tfausak** [comment]
I don't think this is quite fixed yet. This is from `master` (cb4f684e305759c26f71fe6b0e05a0dfbadb91f8):

``` hs
module A
  ( b
  , c)
  where
```
