### ISSUE TITLE
Doesn't support shebangs

### ISSUE THREAD

**Issue by tfausak** [chrisdone/hindent#208]
I tried to run hindent against a [bitrot-free script](https://www.fpcomplete.com/blog/2016/08/bitrot-free-scripts) and got a parse error. 

``` hs
#!/usr/bin/env stack
-- stack runghc
main = pure ()
```

``` sh
> hindent --version
hindent 5.0.0
> hindent Script.hs
hindent: Parse error: #!/
```

**Comment by danielwaterworth** [comment]
This is the corresponding [haskell-src-exts issue](https://github.com/haskell-suite/haskell-src-exts/issues/207)

**Comment by chrisdone** [comment]
I think this can be supported directly in hindent.
