### ISSUE TITLE
Truncates input file

### ISSUE THREAD

**Issue by tfausak** [chrisdone/hindent#217]
``` sh
> echo 'main = pure ()' > Main.hs
> cat Main.hs
main = pure ()
> hindent Main.hs
main = pure ()
> cat Main.hs
> hindent --version
hindent 5.1.0
```

I get that it's supposed to be used in a pipeline style, like `cat Main.hs | hindent`, but the filename arguments are obviously accepted and truncating the file is completely unexpected.

**Comment by chrisdone** [comment]
There's an issue open for this I think.

**Comment by chrisdone** [comment]
#211. Please follow that issue, I'll get to it soon. 👉

**Comment by tfausak** [comment]
They weren't quite the same issue, but 519622bd4ebf6524f00d60ceba0dcb6e1d47e94a fixed this too. Thanks!
