### ISSUE TITLE
'do' keyword gets moved to next indent, pushing things further out

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/hindent#219]
Before hindent:

``` haskell
getCurationTaskR :: UUID -> Handler Html
getCurationTaskR uuid = do
  researcher <- requireResearcher
  (maybeJob, maybeCompany, claimCheck) <- runDB $ do
    Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
    -- ...
```

After hindent:

``` haskell
getCurationTaskR :: UUID -> Handler Html
getCurationTaskR uuid = do
    researcher <- requireResearcher
    (maybeJob,maybeCompany,claimCheck) <-
        runDB $
        do Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
        -- ... etc
```

Pre-hindent version had `runDB $ do` at column 52, so I don't believe (80, 100, 120) col to be a justification here. We usually prefer, and a lot of code I see does this, that the "runner" and the do keyword beginning a block inhabit the same line as the `<-`. Would changing this behavior be amenable?

Also is the non-spacing between the tuple items intentional? Makes reading the tuple bindings a little soupy. Possible my hindent is out of date, but changing that would bring it in line with the deriving clauses as well.

**Comment by chrisdone** [comment]
Spacing in tuples should be fixed in the latest release of 5.1. I just
fixed that today as part of the deriving clauses patch.

Regarding the do with $ I recognise it's a common pattern, but haven't
tried to get it working yet. I'm pretty sure that some logic to hang any do
coming on the right hand side of an operator might do the trick.

**Comment by parsonsmatt** [comment]
> I'm pretty sure that some logic to hang any do coming on the right hand side of an operator might do the trick.

This would move me from skeptical-but-hopeful to frothing-at-the-mouth-fanatic. Any idea of a starting point for this?

**Comment by chrisdone** [comment]
Is this an improvement?

``` haskell
getCurationTaskR :: UUID -> Handler Html
getCurationTaskR uuid = do
  researcher <- requireResearcher
  (maybeJob, maybeCompany, claimCheck) <-
    runDB $
    foobar $ do
      Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
      return x
  foo $ do
    bob
    bill
  return y
```

**Comment by chrisdone** [comment]
I have the following output working:

``` haskell
       getCurationTaskR :: UUID -> Handler Html
       getCurationTaskR uuid = do
         researcher <- requireResearcher
         (maybeJob, maybeCompany, claimCheck) <- runDB $ foobar $$ do
           Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
           return x
         (maybeJob, maybeCompany, claimCheck, foobar) <-
           runDB $
           foobar $$ bob % bill $ do
             Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
             return x
         foo $ do
           bob
           bill
         return y
```

**Comment by chrisdone** [comment]
@parsonsmatt It's a bit tricky this issue to do right, I pushed a WIP branch called `runners` which you can experiment with, though.

**Comment by parsonsmatt** [comment]
I don't like indenting the first term after a bind arrow to the next line. 

```haskell
(maybeJob, maybeCompany, claimCheck, foobar) <-runDB $
           foobar $$ bob % bill $ do
             Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
             return x
```

would be perfect

**Comment by parsonsmatt** [comment]
I'll take a peek at it, thanks :smile:

**Comment by chrisdone** [comment]
@parsonsmatt I think your example there seems a bit arbitrary to decide? That's a real dynamic aesthetic choice; consider `runDB $ runReaderT $` -- that'd also look good on one line, but I don't see a way for the tool to distinguish consistently.

**Comment by bitemyapp** [comment]
@chrisdone It looks good to me, particularly

```haskell
         (maybeJob, maybeCompany, claimCheck) <- runDB $ foobar $$ do
```

is very nice and less spread out than what it did before.

I had the same reaction initially as @parsonsmatt to the "first term after a bind arrow", but having stared at it for a bit, I think your example is the better way forward. It would be a bit tedious to write out, but I think the only way to do it right would be to special-case the LHS of an infix expression to the right of `<-` or to special-case `$` specifically which I think you're trying hard to avoid. I don't think the complexity is worth it but perhaps I am wrong there.

**Comment by chrisdone** [comment]
Oh, I see. Rather than an empty `x <- ` you'd both prefer `x <- foo $` and then a continuation on the next line. @parsonsmatt That said, do you care about the issue raised in my previous comment?

**Comment by parsonsmatt** [comment]
Yup, that's exactly my thought. "First term after bind" is, as far as I can tell, a perfectly good compromise if we need to line break. Especially in the case above, where the line is broken after the first term anyway.

The only sketchy place is if a line break needs to occur right at the arrow, like:

```haskell
-- how I understand the current implementation works:
wat = do
  Just (why, is, this, even, such, a, long, thing) <-
    doTheThing bar baz

-- alternately? kinda gross
orr = do
  Just (why, is, this, even, such, a, long, thing)
    <- doTheThing bar baz

-- I have done this before but I'm not crazy about it
maybe = do
  Just 
    ( why
    , is
    , this
    , even
    , such
    , a
    , long
    , thing
    ) <- doTheThing bar baz
```

though that is really a separate concern, I think

**Comment by chrisdone** [comment]
Closing as original comment is resolved
```
Chriss-MacBook-Pro:hindent chris$ stack exec hindent
getCurationTaskR :: UUID -> Handler Html
getCurationTaskR uuid = do
  researcher <- requireResearcher
  (maybeJob, maybeCompany, claimCheck) <- runDB $ do
    Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
    blah
  sdf
getCurationTaskR :: UUID -> Handler Html
getCurationTaskR uuid = do
  researcher <- requireResearcher
  (maybeJob, maybeCompany, claimCheck) <-
    runDB $ do
      Just (Entity taskKey task) <- fetchThingByField JobTaskUuid uuid
      blah
  sdf
```

**Comment by bitemyapp** [comment]
Cooooool. Thank you :)
