### ISSUE TITLE
Adds trailing whitespace when wrapping

### ISSUE THREAD

**Issue by jml** [chrisdone/hindent#221]
When formatting https://github.com/jml/difftodo/blob/master/git-todo/Main.hs#L106-L114 hindent adds an extra space when wrapping the `comments <- ` line

```diff
 main = do
-  config <- execParser options
-  comments <- case config of
-                Diff False args -> commentsFromDiff args
-                Diff True args  -> commentsFromDiff ("--cached":args)
-                Files args      -> commentsFromFiles args
-  mapM_ (putStrLn . Fixme.formatTodo) (concatMap Fixme.getTodos comments)
+    config <- execParser options
+    comments <- 
+        case config of
+            Diff False args -> commentsFromDiff args
+            Diff True args -> commentsFromDiff ("--cached" : args)
+            Files args -> commentsFromFiles args
+    mapM_ (putStrLn . Fixme.formatTodo) (concatMap Fixme.getTodos comments)
```

This is a minor annoyance, but the space comes up as an error in my emacs config, so would be nice if it that space wasn't there.

Unfortunately Github's syntax highlighter doesn't show it.

**Comment by chrisdone** [comment]
Good catch, that's a bug. I'll get to it next week. Clocking out for this week.

**Comment by chrisdone** [comment]
If you want to take a crack at fixing it, check out here: https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L1226..L1244

And if you fix it, please add an entry under Regression tests here:
https://github.com/chrisdone/hindent/blob/master/TESTS.md#regression-tests

**Comment by danielwaterworth** [comment]
`<- ` isn't the only place where trailing whitespace is added, `= ` and `-> ` do the same.

**Comment by chrisdone** [comment]
@danielwaterworth I fixed those this week.

**Comment by danielwaterworth** [comment]
:smile:
