### ISSUE TITLE
hindent freezes when trying to format this code

### ISSUE THREAD

**Issue by meditans** [chrisdone/hindent#222]
I tried the following function with both the emacs frontend and [the site](http://chrisdone.com/hindent/), and the formatter freezes. Why does this happen? Is this related to the `#` syntax?

``` haskell
c :: forall new. (Settable "pitch" Pitch (Map.AsMap (new Map.:\ "pitch")) new, Default (Book' (Map.AsMap (new Map.:\ "pitch")))) => Book' new
c = set #pitch C (def :: Book' (Map.AsMap (new Map.:\ "pitch")))
```

**Comment by chrisdone** [comment]
Good catch. I can reproduce it with this:

``` haskell
foo :: (Foooooooooooooooooooooooooooooooooooooooooo,Foooooooooooooooooooooooooooooooooooooooooo) => A
```

I believe it's getting stuck due to the length of the constraint.
