### ISSUE TITLE
Alpha sort imports?

### ISSUE THREAD

**Issue by jml** [chrisdone/hindent#223]
I don't know if this is a desired feature or not, but it would help `hindent` approach `gofmt`-like functionality.

Current import formatting preserves order:

``` diff
 import qualified Data.ByteString as ByteString
 import GHC.IO (FilePath)
 import Text.Highlighter
-  ( lexerFromFilename
-  , runLexer
-  , Lexer
-  , Token(..)
-  , TokenType(..)
-  )
-
+       (lexerFromFilename, Token(..), runLexer, Lexer, TokenType(..))
```

It'd be nice if it alpha sorted them in some way that's consistent.

**Comment by chrisdone** [comment]
I think that's a pretty reasonable idea.

**Comment by sighingnow** [comment]
I think the functionality of [stylish-haskell](https://github.com/jaspervdj/stylish-haskell) or something like should be implemented in hindent. I remember that this feature was supported by cramer style of hindent 4.x.

@chrisdone Is there any plan to support this feature in future version of hindent ?

**Comment by chrisdone** [comment]
@sighingnow support what exactly?

**Comment by sighingnow** [comment]
+ Sort `{-# LANGUAGE #-}` pragmas and remove redundant ones.
+ Group imports in the order as described in [Johan Tibell style guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#imports) and sort them alphabetically.

The stylish-haskell package has provided a gold example [here](https://github.com/jaspervdj/stylish-haskell#example).

**Comment by chrisdone** [comment]
> Sort `{-# LANGUAGE #-}` pragmas and remove redundant ones.

That can be done. I'd accept a PR for that, fiddle with the pragmas [here](https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L1030), I think, should do the trick. 

> Group imports in the order as described in [Johan Tibell style guide](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md#imports) and sort them alphabetically.

I think that grouping isn't a thing, see:

``` haskell
bash-3.2$ stack exec stylish-haskell
import Foo
import Data.List
import Bar
^D
import           Bar
import           Data.List
import           Foo
```

It merely sorted the group alphabetically. We can sort each group of imports alphabetically. 

One problem: I think that if there is a comment on a line in-between imports, then we have a sorting problem. It may be prudent to skip groups with comments on a line.

**Comment by sighingnow** [comment]
How about aligning imports like stylish-haskell? For example,

Before formatting:
~~~haskell
import qualified Data.Map as M
import Data.Map    ((!), keys, Map)
~~~
After formatting:
~~~haskell
import qualified Data.HashMap as M
import           Data.Map     ((!), keys, Map)
~~~

**Comment by tfausak** [comment]
For what it's worth, I despise aligning imports like that. If you change `Data.HashMap` to `Data.HashMap.Strict`, every other line has to change to preserve alignment.

**Comment by chrisdone** [comment]
I'm also not personally a big fan of aligning anymore. I used to (implemented such a feature in Emacs), but, like @tfausak I found it creates awkward gaps or changing n lines just because of one. 

This might be a good case for a command-line flag like `--align-imports` which is turned off by default, but which you could enable with some kind of `.hindent` file.

**Comment by sighingnow** [comment]
Or, do something like the source code of hindent ifself? For example, [Pretty.hs](https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L15) and [Types.hs](https://github.com/chrisdone/hindent/blob/master/src/HIndent/Types.hs#L19), and the code above should be formatted as follow @chrisdone @tfausak :

~~~haskell
import qualified Data.HashMap as M
import           Data.Map ((!), keys, Map)
~~~

**Comment by tfausak** [comment]
Why stop at adding a flag? Why not make a different style? :wink: 

[The current format](https://github.com/chrisdone/hindent/blob/34ad36c20ade8b6e8fb5a157b12e15c4a6c5e1ca/TESTS.md#imports) is what I prefer. 

``` hs
import Data.Text
import qualified Data.Text as T
import qualified Data.Text (a, b, c)
import Data.Text (a, b, c)
import Data.Text hiding (a, b, c)
```

**Comment by chrisdone** [comment]
I'm probably not going to implement this any time soon. If anyone wants it, please PR it.
