### ISSUE TITLE
Newline-separated list gets flattened

### ISSUE THREAD

**Issue by jml** [chrisdone/hindent#224]
Not sure if this is a bug or intended behaviour:

```diff
 defaultTags :: [Text]
-defaultTags = [ "XXX"
-              , "TODO"
-              , "FIXME"
-              ]
+defaultTags = ["XXX", "TODO", "FIXME"]
```

I deliberately newline separated the list, and hindent flattened it into one line.

Not super important to me, but would be really nice to have.

(This is the last one of these issues: really liking hindent 5.1.0).

**Comment by chrisdone** [comment]
That one's intentional. It newline-separates when the list gets big, and makes it small again when it's small. Is this a deal-breaker?

**Comment by jml** [comment]
Not a deal breaker per se (there's a lot I'd be willing to give up to never
have to think or talk about formatting ever again) but it's definitely
surprising.

I'm not at my laptop so I can't find an example, but gofmt preserves the
line breaks in literal data structures (esp struct initialisations), and
this behaviour seems less surprising to me, although this is admittedly
subjective.

**Comment by chrisdone** [comment]
It's just an extra tricky bit of work to implement preserving line-breaks. I'll close for now but maybe we can return to it after hindent 5 has all its bugs ironed out.

**Comment by jml** [comment]
Fair call. Just adding another example which maybe provides a better motivation for the feature request:

```haskell
        let expected = [ comment "# first comment", eol
                       , eol
                       , comment "# second comment", eol
                       , comment "# is multi-line", eol
                       , eol
                       , Token (Literal :. Number :. Integer) "1", text " ", Token Operator "+", text " ", Token (Literal :. Number :. Integer) "2", text "  ", comment "# trailing comment", eol
                       ]
```

Here, the list is a list of tokens. When I hit an EOL in the token stream, I put a newline in the list in code to make the whole thing more readable. I could probably work around this by putting it into a list of lists or something, but updating data structures to comply better with the formatter seems a little backwards.
