### ISSUE TITLE
Newline before end of list?

### ISSUE THREAD

**Issue by tfausak** [chrisdone/hindent#228]
Lists are currently formatted like this:

``` hs
exceptions =
    [ InvalidStatusCode
    , MissingContentHeader
    , InternalServerError
    , InvalidStatusCode
    , MissingContentHeader
    , InternalServerError]
```

I think there should be a newline before the closing bracket, like this:

``` hs
exceptions =
    [ InvalidStatusCode
    , MissingContentHeader
    , InternalServerError
    , InvalidStatusCode
    , MissingContentHeader
    , InternalServerError
    ]
```

**Comment by chrisdone** [comment]
I think that'd be consistent with other additions recently. No disagreement. Want to send a PR? Gotta go AFK for a bit.

**Comment by chrisdone** [comment]
Relevant code: https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L502

**Comment by bergmark** [comment]
I was just going to file this! I find it much easier to get an overview of the whole list if the separators are in the same column. Looking at the test suite it's also consistent with export lists and records.

I don't see an example of long import lists in the test suite, the demo gives 
```
import A
       (foobarbazqux, foobarbazqux, foobarbazqux, foobarbazqux,
        foobarbazqux, foobarbazqux, foobarbazqux)
```

which creates *even more* inconsistency ;-)

How about

```haskell
import A
 ( foobarbazqux, foobarbazqux
 , foobarbazqux, foobarbazqux
 )
```

or even

```haskell
import A
 ( foobarbazqux
 , foobarbazqux
 , foobarbazqux
 , foobarbazqux
 )
```

? Maybe I'm pushing it.


Are there other lists that I'm forgetting about?

**Comment by chrisdone** [comment]
> or even

```haskell
import A
 ( foobarbazqux
 , foobarbazqux
 , foobarbazqux
 , foobarbazqux
 )
```

That seems pretty reasonable to me. It should either be `import A (x, y, z)` or if that doesn't fit in 80 columns, go to the next line. 👍
