### ISSUE TITLE
Wonky multiline comment handling

### ISSUE THREAD

**Issue by bitemyapp** [chrisdone/hindent#231]
```haskell
module Woo where

hi = "hello"

{-
test comment
-}

-- blah blah
-- blah blah
-- blah blah
```

Is incorrectly transformed into:

```haskell
module Woo where

hi = "hello"
--
test comment

-- blah blah
-- blah blah
 -- blah blah
```
(note the weird space in front of `-- blah blah` in addition to the inappropriate elision of the `{- -}` pairing)

**Comment by chrisdone** [comment]
Right, I need to add back multi-line comments. Forgot about that. Cheers!

**Comment by chrisdone** [comment]
Fixed the multi-line comment rendering.

That extra space on the last line of a module I think is a consequence of HSE parsing that last comment as coming "after" the end of the module, so hindent things it's a comment "on the same line" as the module. I'll probably add some special logic to handle that as it bugs me too.

**Comment by chrisdone** [comment]
``` haskell
Module {- [CommentSameLine (EndOfLine " \965")] -} Nothing [] [] [PatBind  (PVar  (Ident  "\945")) (UnGuardedRhs  (InfixApp  (Var  (UnQual  (Ident  "\947"))) (QVarOp  (UnQual  (Symbol  "*"))) (Lit  (String  "\969" "\969")))) Nothing]
```

Yeah, in `α = γ * "ω" -- υ` it thinks `-- υ` comes at the end of the module on the same line.
