### ISSUE TITLE
`deriving` keyword not aligned with pipe symbol for type declarations

### ISSUE THREAD

**Issue by radupopescu** [chrisdone/hindent#233]
When I have a declaration for a sum type, deriving is aligned one space after the pipe. Ex:

```haskell
data Stuffs
    = Things
    | This
    | That
     deriving (Show)
```

I'm not sure this is normal. The leading space is also inserted for declarations without pipes:

```haskell
data Simple =
    Simple
     deriving (Show)
```

**Comment by oldmanmike** [comment]
Same issue.

**Comment by chrisdone** [comment]
Good catch, subtle. Hadn't noticed it.

**Comment by radupopescu** [comment]
Thanks again! Great job on this project and intero, too.

**Comment by chrisdone** [comment]
Had to update the tests -- we're switching over to 2-spaces by default. 

See [the README](https://github.com/chrisdone/hindent#customization) if you'd like to specify 4 spaces.
