### ISSUE TITLE
Tuple spacing is inconsistent

### ISSUE THREAD

**Issue by iand675** [chrisdone/hindent#234]
After running hindent on a file, it produced the following result:

```
swap (x,y) = (y, x)
```

Note how there's no space after the comma on the LHS, but there is on the RHS. This is personal opinion, but I strongly prefer having a space after commas. In any case, settling on one or the other seems favourable.

**Comment by mrBliss** [comment]
I cannot reproduce this with HEAD.

**Comment by chrisdone** [comment]
@mrBliss You're right, thanks for checking!
