### ISSUE TITLE
Wrapped import list shouldn't add newline

### ISSUE THREAD

**Issue by cblp** [chrisdone/hindent#241]
```haskell
import TooLongList
       (alpha, beta, gamma, delta, epsilon, zeta, eta, theta)
import Test
```

hindent writes:
```haskell
import TooLongList
       (alpha, beta, gamma, delta, epsilon, zeta, eta, theta)

import Test
```

The problem is in `HIndent.Pretty.formatImports`: one can't compare start points of multi-line import lists.

Are end points available?

**Comment by chrisdone** [comment]
@cblp End points are available too: `srcSpanStart` and `srcSpanEnd`

**Comment by cblp** [comment]
@chrisdone end point of import construction? There is only annotation, I don't know what it is.

**Comment by chrisdone** [comment]
The `ImportDecl` have a `NodeInfo` in them: https://github.com/chrisdone/hindent/blob/master/src/HIndent/Types.hs#L104..L104

Which is accessible via `ann`, like here: https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L1098..L1099

This code

``` haskell
(srcSpanStart (srcInfoSpan (nodeInfoSpan (ann current))))
```

is the start point `(line::Int,col::Int)` of the `current` node.

**Comment by cblp** [comment]
It works!
