### ISSUE TITLE
The atom plugin doesn't seem to work

### ISSUE THREAD

**Issue by sgraf812** [chrisdone/hindent#246]
By 'doesn't seem to work' I mean styling up a file simply erases all content for me.

Fortunately, you can use https://atom.io/packages/ide-haskell with the path to `hindent` specified instead of that to `stylish-haskell`. Works like a charm that way!

**Comment by chrisdone** [comment]
We'll have to update the README!

**Comment by chrisdone** [comment]
Updated the readme,
