### ISSUE TITLE
Should indendation options be removed?

### ISSUE THREAD

**Issue by MichaelXavier** [chrisdone/hindent#248]
Thought I'd give hindent a spin today (Hindent 5.2.0, elisp package version 20160830.552 installed today) and it looks like the plugins are out of sync. I think even if you set the defaults, it calls the command `hindent --indent-size 2 MYFILE`, and current hindent treats `--indent-size` as the filename and throws `--indent-size: openBinaryFile: does not exist` rendering the plugin unable to format any files. I could take a crack at removing the option if you'd like.

**Comment by chrisdone** [comment]
Perhaps we can just remove all options from emacs and leave that to the
.hindent.yaml file. Go ahead!
