### ISSUE TITLE
hindent-20160830.552 on melpa and hindent-5.1.1 aren't compatible

### ISSUE THREAD

**Issue by sooheon** [chrisdone/hindent#249]
I'm getting the following when trying to format with M-q:

```
if: hindent: --indent-size: openBinaryFile: does not exist (No such file or directory)
```

Commenting out L196~199, the `(when hindent-indent-size...` sexp, resolves the problem and I can hindent in buffers again.

**Comment by tfausak** [comment]
Sounds the same as #248.
