### ISSUE TITLE
Emacs integration doesn't respect `~/.hindent.yaml`

### ISSUE THREAD

**Issue by gromakovsky** [chrisdone/hindent#257]
At least `indent-size` is not respected. My `~/.hindent.yaml` is:
```
indent-size: 4
line-length: 80
force-trailing-newline: true
```

If I use it from command line, everything is fine, indent size is really 4. However, when I use it in emacs (`M-q`), indent size is 2.

I am using last version of hindent built locally (currently 2da31a5df1c2ef956b33439a03a6acd99415f2ee which is 5.2). Emacs package is also 5.2 from melpa.

**Comment by chrisdone** [comment]
Grab the latest hindent Emacs version, that'll fix it! Related https://github.com/chrisdone/hindent/issues/248

**Comment by gromakovsky** [comment]
Ok, thx, it helped. 

I saw that issue but didn't realize that it would fix my problem as well.

**Comment by adithyaov** [comment]
Hi, I have the same problem. My emacs does not respect `~/.hindent.yaml`. Surprisingly it respects `$PROJECT_ROOT/.hindent.yaml` though.

I'm running emacs 26.3 on Windows WSL but using XServer for GUI.
