### ISSUE TITLE
Bad formatting: comment inside list comprehension

### ISSUE THREAD

**Issue by cblp** [chrisdone/hindent#260]
I'm trying to fix handling of this snippet
``` haskell
defaultExtensions =
  [ e
  | e@EnableExtension {} <- knownExtensions
  , let var = val
    -- comment
  ]
```

Any pointers?

----

       expected: 
       defaultExtensions =
         [ e
         | e <- knownExtensions
         , let a = b
           -- comment
         , let c = d
           -- comment
         ]
        but got: 
       defaultExtensions =
         [ e
         | e <- knownExtensions 
         , let a = b
          -- comment
           
         , let c = d
          -- comment
           ]
       The diff:
       3c3
       <   | e <- knownExtensions
       ---
       >   | e <- knownExtensions 
       5c5,6
       <     -- comment
       ---
       >    -- comment
       >     
       7,8c8,9
       <     -- comment
       <   ]
       ---
       >    -- comment
       >     ]

**Comment by cblp** [comment]
I'm patching `Pretty.exp ListComp{}`. Found `unless (null qstmt)`. When qstmt may be null?

**Comment by cblp** [comment]
@chrisdone I'm patching Pretty.exp ListComp{}. Found unless (null qstmt). When qstmt may be null?

**Comment by chrisdone** [comment]
Not sure. The unless may be redundant.
