### ISSUE TITLE
Shall we address all FIXME/No implementations?

### ISSUE THREAD

**Issue by ocharles** [chrisdone/hindent#292]
I'm happy to go through `Pretty.hs` write now and provide *something*. I'm not going to suggest it's necessarily the best style, but I think it's better that `hindent` is usable on as many files as possible. We can refine the styling case-by-case later.

If you're OK with this, I'll carry on and give you a pull request shortly.

**Comment by chrisdone** [comment]
Sounds good to me! As long as it's accompanied by test cases in TESTS.md, we can see what the state of the changes are.

**Comment by ocharles** [comment]
Yea, plan to have everything tested too
