### ISSUE TITLE
Hindent produces unparsable code

### ISSUE THREAD

**Issue by NorfairKing** [chrisdone/hindent#296]
When I run `hindent` on this code: 

https://github.com/NorfairKing/super-user-spark/blob/master/src/Parser/Internal.hs

The first time everything is fine, but the second time I get this:

```
hindent: src/Parser/Internal.hs: Parse error in expression: return $ Block ds <?>
```

**Comment by ivan-timokhin** [comment]
In case that helps, I think I've found something resembling a minimal test case.
This code:
```haskell
do x <- [1,2]
   return x
   ++ [3]
```
is, somewhat surprisingly (for me at least), correctly parsed by `ghc` as `(do ...) ++ [3]`

However, `hindent` turns it into
```haskell
do x <- [1,2]
   return x ++
[3]
```
which no longer parses correctly.

**Comment by NorfairKing** [comment]
This is a showstopper. Is there any progress ?

**Comment by chrisdone** [comment]
The workaround is you can put parens around the `do`. But yeah, this needs fixing.

**Comment by NorfairKing** [comment]
Would it help if I added a failing test case?

**Comment by NorfairKing** [comment]
I am still waiting to start using hindent until this is fixed.

**Comment by NorfairKing** [comment]
Confirmed fixed.

**Comment by NorfairKing** [comment]
Thanks!
