### ISSUE TITLE
Too long lines?

### ISSUE THREAD

**Issue by joncol** [chrisdone/hindent#300]
Hi, thanks for your nice program!

But I am annoyed that the following (too long) line isn't correctly split up over several lines.

``` haskell
getPrefix = fmap (fst . span (not . isDigit)) . stripPrefix "Bank " . takeBaseName
```

I've configured my max length to be 80.

**Comment by chrisdone** [comment]
For me it goes to the next line. What version of hindent are you using?

```
Chriss-MBP:~ chris$ cat > demo.hs
getPrefix = fmap (fst . span (not . isDigit)) . stripPrefix "Bank " . takeBaseName
Chriss-MBP:~ chris$ cat demo.hs | ~/.local/bin/hindent
getPrefix =
  fmap (fst . span (not . isDigit)) . stripPrefix "Bank " . takeBaseName
```

**Comment by IvanMalison** [comment]
@chrisdone hindent will move things to the next line, but it wont break up an expression across multiple lines when that is called for.

``` haskell
$ hindent --version
hindent 5.2.1
$ cat hindent.hs | hindent
selectToggle =
  togglesMap >>= DM.menuMapArgs "rofi" ["-dmenu", "-i"] >>= flip whenJust sendMessage
```

**Comment by IvanMalison** [comment]
not only that, it will actually undo multi-lining across multiple lines
