### ISSUE TITLE
blog post says default indent is 4 but github README and code say 2

### ISSUE THREAD

**Issue by haroldcarr** [chrisdone/hindent#304]
The blog post http://chrisdone.com/posts/hindent-5 says:

"The most popular style in the community2 is JohanTibell: The alignment, line-breaking, and spacing (4 spaces instead of 2) differs significantly to my own style."

But the github README and `hindent/src/HIndent/Types.hs` `defaultConfig` say 2.

**Comment by tfausak** [comment]
It was accurate when it was written. And if anything, this should be a bug against https://github.com/chrisdone/chrisdone-homepage.

**Comment by haroldcarr** [comment]
According to tibbe's style guide: 

https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md 

"Indent your code blocks with 4 spaces."

But now I see the the blog post says: "based on the Johan Tibell style guide." - so I guess Chris decided to go with his preferred 2 spaces rather than Johns 4 spaces.

**Comment by tfausak** [comment]
He polled the community about their preferred indent size. See #236.

**Comment by haroldcarr** [comment]
Thanks for pointing that out - missed it.  Case closed.
