### ISSUE TITLE
Don't put line breaks between empty instances

### ISSUE THREAD

**Issue by enolan** [chrisdone/hindent#325]
When using generics it's common to have a long list of empty instance declarations. For instance, from Idris's `DeepSeq` module:

``` haskell
instance NFData a => NFData (D.Docstring a)
instance NFData ConsoleWidth
instance NFData PrimFn
```

That goes on for 52 lines. Hindent currently puts a newline between each one, which to my eye doesn't make it any more readable.

**Comment by chrisdone** [comment]
Exceptions to the rules just make things harder.
