### ISSUE TITLE
Please support in-place formatting with a flag

### ISSUE THREAD

**Issue by MedeaMelana** [chrisdone/hindent#327]
Right now it seems hindent will only write output to stdout, which is fine for editor support.
But I'd like to run hindent myself from the command line, and it would be nice if there was a way to run hindent on a file in a single command.
Currently I have to write the output to a temporary file, then replace the original file with the contents of the temporary file. If there was an --in-place flag (or similar) that would replace the contents of the input file, that'd be really useful!

**Comment by tfausak** [comment]
Doesn't hindent work in-place already? 

``` sh
tmp> echo 'f x=x' > Example.hs
tmp> hindent Example.hs
tmp> cat Example.hs
f x = x
```

It only writes to STDOUT if you pipe to STDIN.

``` sh
tmp> hindent < Example.hs 
f x = x
tmp> cat Example.hs | hindent
f x = x
```

**Comment by MedeaMelana** [comment]
You are absolutely right. Not sure how I missed this. Thanks!
