### ISSUE TITLE
FIXME: No implementation for TypeApp

### ISSUE THREAD

**Issue by k-bx** [chrisdone/hindent#329]
Apparently, type applications are not implemented in hindent, and I couldn't find any issue about it, so I'm creating this one. Thanks!

**Comment by ElvishJerricco** [comment]
This is the only reason I'm not using `TypeApplications` in a personal project.

**Comment by gromakovsky** [comment]
@chrisdone 
It was fixed on September 6, but version is still the same and it forces people to install `hindent` from source which is inconvenient. Why not increase version because of this fix?

**Comment by chrisdone** [comment]
Bumped to 5.2.2.
