### ISSUE TITLE
Switch from haskell-src-exts to ghc-exactprint

### ISSUE THREAD

**Issue by cblp** [chrisdone/hindent#338]
## [`ghc-exactprint`](https://github.com/alanz/ghc-exactprint) advantages
1. Will always be up-to-date with GHC.
2. Already parses comments and places them properly into AST.
## `haskell-src-exts` advantages

0

---

I love the idea behind `hindent`. But I want comments in my code to be reformatted properly.

So let's switch!

If we decide to switch to `ghc-exactprint` I can help (or even do all the work on rewriting, maybe).

If we decide to stick with `haskell-src-exts` I will have to switch to [`brittany`](https://github.com/lspitzner/brittany) or fork `hindent`.

---

I summon @chrisdone

**Comment by tfausak** [comment]
Clickable:
[ghc-exactprint](https://github.com/alanz/ghc-exactprint)
[brittany](https://github.com/lspitzner/brittany)

**Comment by cblp** [comment]
@tfausak, updated, thanks

**Comment by cblp** [comment]
:(

**Comment by int-index** [comment]
@chrisdone Silently closing issues is not very polite.

**Comment by Tehnix** [comment]
Why was this closed? Currently this would solve https://github.com/commercialhaskell/hindent/issues/455, https://github.com/commercialhaskell/hindent/issues/439, https://github.com/commercialhaskell/hindent/issues/400, https://github.com/commercialhaskell/hindent/issues/220, https://github.com/commercialhaskell/hindent/issues/316 and probably https://github.com/commercialhaskell/hindent/issues/456 and https://github.com/commercialhaskell/hindent/issues/370.

I honestly run into the comment issue so frequently, and if hindent wants to become the defacto formatter, breaking comments in the way it does is simply too breaking.

**Comment by tfausak** [comment]
For what it's worth, I'm trying to switch to Brittany now that this PR has landed: https://github.com/lspitzner/brittany/pull/66

**Comment by chrisdone** [comment]
@Tehnix Rewriting in GHC API would be making a new project entirely. I already wrote hindent once, I don't feel like doing it again. Feel free to try out Brittany. HIndent works for me. I might just spend a weekend one day fixing comments, but I'm certainly not going to rewrite the whole project.

**Comment by Tehnix** [comment]
@chrisdone Fair point :) I wasn't entirely sure how intrusive it would be since it seemed ghc-exactprint was somewhat related to haskell-src-exts.
