### ISSUE TITLE
not working at all

### ISSUE THREAD

**Issue by nitingupta910** [chrisdone/hindent#339]
Using Ubuntu 16.04

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.3

Installed hindent using
`stack update`
`stack install hindent`

$ echo 'example = case x of Just p -> foo bar' | hindent --indent-size 2; echo

`
hindent: --version --style (fundamental|chris-done|johan-tibell|gibiansky|cramer) --line-length <...> [-X<...>]* [<FILENAME>]
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:59:10 in main:Main
`

**Comment by nitingupta910** [comment]
I see that it works if I do pass in a style parameter like:
`echo 'example = case x of Just p -> foo bar' | hindent --style gibiansky`

I think examples in README.md should be updated to reflect this.

**Comment by cdepillabout** [comment]
@nitingupta910 What version of `hindent` are you using?  It looks like you are using something <5.0.  I don't think those versions are being are being maintained/supported anymore.

You can install a version of `hindent` >5.0 with a command like this:

```sh
$ stack install --resolver nightly-2016-10-17 hindent
```

**Comment by nitingupta910** [comment]
I was using hinding 4.6.4. With stack nightly resolver I got hindent 5.2.1 which works as mentioned in README. Thanks @cdepillabout.

**Comment by thejohnfreeman** [comment]
5.2.1 doesn't work for me. What am I missing?

```shell
$ hindent --version
hindent 5.2.1
$ cat example.hs | hindent
hindent: Parse error: ;
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:62:21 in main:Main
```

```hs
data Rocks =
Rocks String deriving (Eq, Show)
data Yeah =
Yeah Bool deriving (Eq, Show)
data Papu =
Papu Rocks Yeah
deriving (Eq, Show)
```
