### ISSUE TITLE
operators at start of line

### ISSUE THREAD

**Issue by cspollard** [chrisdone/hindent#365]
Hi,

Is it possible to have operators appear at the beginning of a line rather than the end?

For instance the following code is formatted by hindent:

```haskell
logFactorial
    :: (Integral a, Floating b)
    => a -> b
logFactorial k
  | k < 0 = error "logPoiss: negative integer input!"
  | k <= 14 = log . fromIntegral $ factorial k
  | otherwise = 
      (x - 0.5) * log x - x + lnsqrt2pi + 1 / (12 * x) -
      1 / (360 * x ^ 3) +
      1 / (1260 * x ^ 5) -
      1 / (1680 * x ^ 7)
  where
    x = fromIntegral (k + 1)
    lnsqrt2pi = 
        0.9189385332046727417803297364056176398613974736377834128171
    factorial 0 = 1
    factorial 1 = 1
    factorial n = n * factorial (n - 1)
```

In particular the block

```haskell
      (x - 0.5) * log x - x + lnsqrt2pi + 1 / (12 * x) -
      1 / (360 * x ^ 3) +
      1 / (1260 * x ^ 5) -
      1 / (1680 * x ^ 7)
```

would be much clearer (in my opinion) written as

```haskell
      (x - 0.5) * log x - x + lnsqrt2pi
      + 1 / (12 * x)
      - 1 / (360 * x ^ 3)
      + 1 / (1260 * x ^ 5)
      - 1 / (1680 * x ^ 7)
```

ie. with the (arithmetic) operators at the *start* of the lines. Is it possible to do this already with the current options? If not, can we make it possible? I'm happy to try to make the change myself with some direction from the devs.

Chris

**Comment by chrisdone** [comment]
I'm not going to change existing code that works for this reason.

**Comment by cspollard** [comment]
Hi @chrisdone,

I'm not sure I understand your comment. Generally speaking (IMO) it makes sense to put operators with low precedence at the _beginning_ of lines since they encode the overall structure of a line. Currently one has to scan all the way to the end of a line to find the "connecting" operator. Is there some reason we can't change this?

Chris
