### ISSUE TITLE
Hindent produces unparseable code when splitting line after `<$>`

### ISSUE THREAD

**Issue by berdario** [chrisdone/hindent#368]
I was trying out the different styles, to see which one is closer to the one that I'm currently using, and I was doing it by appliying hindent over and over (I then realized that it's better to `git checkout HEAD` after every change, since hindent's changes depend on the source formatting)

I reduced the test case to this one:

```haskell
loooooooooooooooooooooooooongshow = show

looooooooooooooooooooooooooooooongpure = pure

f = do loooooooooooooooooooooooooongshow <$> looooooooooooooooooooooooooooooongpure 42
```

By saving it as `foo.hs` and running

```
hindent --style chris-done  foo.hs ; hindent --style gibiansky  foo.hs ; hindent --style gibiansky  foo.hs
```

You'll end up with 

```haskell
loooooooooooooooooooooooooongshow = show

looooooooooooooooooooooooooooooongpure = pure

f =
  do
    loooooooooooooooooooooooooongshow <$>
    looooooooooooooooooooooooooooooongpure 42
```

Which yields a `Parse error in expression: loooooooooooooooooooooooooongshow <$>`

**Comment by sighingnow** [comment]
It seems that this problem has already been fixed in the newest code. @berdario You could pull the latest code from Github and take a try. This example will be formatted as:

~~~haskell
loooooooooooooooooooooooooongshow = show

looooooooooooooooooooooooooooooongpure = pure

f = do
  loooooooooooooooooooooooooongshow <$>
    looooooooooooooooooooooooooooooongpure 42
~~~

**Comment by berdario** [comment]
Uh, you're right...

I was running hindent 4.6.4 (from LTS-6.22), but now that I compiled master (version 5.2.1) the problem disappeared

thank you!
