### ISSUE TITLE
Parse fails on OVERLAP pragma

### ISSUE THREAD

**Issue by siddharthist** [chrisdone/hindent#385]
Unfortunately, `hindent` gets caught in [the same bug](https://github.com/jaspervdj/stylish-haskell/issues/150) as `stylish-haskell`! 
```
hindent: src/XXX/Util.hs: Parse error: {-# OVERLAP
CallStack (from HasCallStack):
  error, called at src/main/Main.hs:47:23 in main:Main
```

Do you use the same parser? If not, you might want to consider it (to reduce duplicated work keeping up with new GHC changes)!

**Comment by siddharthist** [comment]
Sorry, this was my error!

**Comment by ptek** [comment]
I had a similar issue.

Hindent changes the code of:

```haskell
instance {-# OVERLAPPING #-} Arbitrary (Set Int) where
    arbitrary = ...
```

into 

```haskell
instance Arbitrary (Set Int) {-# OVERLAPPING #-}
                             where
    arbitrary = ...
```

So when compiling, GHC rightfully complains that it can’t parse `{-# OVERLAPPING`
