### ISSUE TITLE
Add hindent to Stackage

### ISSUE THREAD

**Issue by AKurilin** [chrisdone/hindent#47]
Hey folks, I was hoping you might add hindent to [Stackage](https://github.com/fpco/stackage) so that those of us on it can use the tool as well.

Looks like [this is already in the works](https://github.com/fpco/stackage/blob/master/Stackage/Config.hs#L345), but I figured we might as well have this issue for tracking purposes.

I believe this depends on [issue 9](https://github.com/chrisdone/hindent/issues/9)

**Comment by chrisdone** [comment]
Added now.

**Comment by AKurilin** [comment]
Cheers!
