### ISSUE TITLE
Parse error on `proc` (chris-done)

### ISSUE THREAD

**Issue by osener** [chrisdone/hindent#51]
I'm trying to format this expression (which uses `System.Process.proc`) and getting "hindent: Parse error: [" in emacs:
```hs
    ((toProcess, close), fromProcess, ClosedStream, cph) <-
        streamingProcess (proc "base64" [])
```

It can be reduced to `proc "" []`

**Comment by chrisdone** [comment]
I think we can fix this with an extensions section in a config file.

**Comment by mgsloan** [comment]
I've definitely run into this before, but instead with shm.

**Comment by chrisdone** [comment]
I've implemented providing extensions to the executable matching with hlint's method in structured-haskell-mode: https://github.com/chrisdone/structured-haskell-mode/issues/70#issuecomment-70372256

I'll do the same for hindent. Then separately we can make Emacs pass in extensions to the executable by getting them from *some* source (e.g. scanning the file, using a project-local variable, asking GHCi, parsing the cabal file, etc.).

**Comment by chrisdone** [comment]
Okay, implemented here. Now `-XArrows` and others are disabled, like in hlint. Then they can be re-enabled by passing `-XFoo` to hindent. I'll implement Emacs support next.

**Comment by osener** [comment]
This is great, thank you!
