### ISSUE TITLE
Comments on declarations in where clause not correct

### ISSUE THREAD

**Issue by lippirk** [chrisdone/hindent#540]
- [x] I checked the issue tracker for existing issues about this problem.
- [x] I'm using the latest version of hindent (checked latest commit on master).

## Problem

There is a corner case where comments on the first declaration in a where clause are placed above the where keyword rather than above the declaration. It's probably easiest to see from my example below

Input haskell
```haskell
topLevelFunc = f
  where
    -- comment
    f = undefined
```

Expected: no change

Actual output haskell
```haskell
topLevelFunc1 = f
  -- comment
  where
    f = undefined
```

**Comment by lippirk** [comment]
I've made a pull request #541

**Comment by normenmueller** [comment]
I guess this problem is not solely related to `where` clauses:

```haskell
data Record = Record
    { -- | This is a very very very long comment that is split over
      -- multiple lines.
      field1 :: !Text

      -- | This is a second very very very long comment that is split
      -- over multiple lines.
    , field2 :: !Int
    }

main :: IO ()
main = do
    -- Misc
    counter 10
```

Hindent then yields the following

```haskell
data Record = Record
      -- | This is a very very very long comment that is split over
      -- multiple lines.
    { field1 :: !Text
      -- | This is a second very very very long comment that is split
      -- over multiple lines.
    , field2 :: !Int
    }

main :: IO ()
main
    -- Misc
 = do
    counter 10
```

**Comment by lippirk** [comment]
A workaround i have been using is to instead put comments below instead, i.e.

```
data Record = Record
    { field1 :: !Text
      -- | This is a second very very very long comment that is split
      -- over multiple lines.
    , field2 :: !Int
      -- | This is a second very very very long comment that is split
      -- over multiple lines.
    }
```

should work

**Comment by lippirk** [comment]
iirc information about the comments gets lost along the way when hindent parses the file, so there are always going to be issues while that is the case

**Comment by lippirk** [comment]
Closing in favour of #511
