### ISSUE TITLE
There is no git tag for the latest release

### ISSUE THREAD

**Issue by NorfairKing** [chrisdone/hindent#543]
I'm trying to find the right commit for `5.2.7` but I'm not sure which commit was used to release that version.

**Comment by chrisdone** [comment]
The bump to 5.2.7 was here in e68db19. I forgot to tag that commit, so I've tagged it now. 

Meanwhile, looks like it's time to make a new release too.

**Comment by chrisdone** [comment]
Published as 5.3.0 and tagged.

**Comment by NorfairKing** [comment]
Super, thanks!
