### ISSUE TITLE
Consider (eventually) migrating to GHC API instead of HSE

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/hindent#56]
It looks like with Alan's work in GHC 7.10, the API annotations are able to round-trip from source back to source without changing any formatting (besides trailing whitespace). This is pretty cool, and better than we can do with HSE right now. Perhaps it makes sense to consider eventually migrating to the GHC API, once GHC 7.10 is out and in common use?

**Comment by chrisdone** [comment]
>  the API annotations are able to round-trip from source back to source without changing any formatting (besides trailing whitespace). This is pretty cool, and better than we can do with HSE right now

Explain?

**Comment by gibiansky** [comment]
HSE's source locations are not very good. There are a number of cases where it is very difficult to recover the exact code layout, if possible at all. In addition, using GHC would mean that all extensions are supported and we should never have parse errors on code that is valid.

On the other hand, GHC API can be a real pain to use, so might not be worth it.

**Comment by chrisdone** [comment]
We're not using source locations for anything… But yeah, parsing anything GHC supports would be handy. I believe Alan removed the landmines from the AST, which is useful to make the GHC AST usable once 7.10 is common-place.

**Comment by chrisdone** [comment]
Oh, this would also have the added benefit of resolving infix operators properly.

**Comment by mgsloan** [comment]
This'd definitely be the right way to go, as then we're only using one consistent parser for code.  It's awesome that Alan is making it usable + extending its functionality.

I'm not sure if using GHC's resolution would be the best thing, though, as then scope errors could prevent hindent from running.  The purpose of resolving infix operators would be to do operator specific layout, right?  E.g. lining up applicative style.  I think that it wouldn't be hard to do this by analyzing the imports list, and ignoring the possibility of defining operators in where / let clauses.  So, it ought to be possible to just use GHC's parser and nothing more.

I suppose getting operator fixities could be helpful in the event that some hindent styles also modify parenthesization.

**Comment by gibiansky** [comment]
@chrisdone The `gibiansky` style actually does use source locations. This gives the user some flexibility in how they want to add spacing to, say, `do` blocks or groups of `let` statements, which can be important for grouping declarations or statements according to their semantic meanings. IMHO this is actually a very important feature.

**Comment by gibiansky** [comment]
To clarify, it uses source locations in order to try to preserve original user formatting.
