### ISSUE TITLE
hindent not on melpa

### ISSUE THREAD

**Issue by tonyday567** [chrisdone/hindent#58]
Is there a reason why hindent is not on any of the emacs package sites?

I'm doing a fresh install of emacs and am trying to be neat.  For other emacs/haskell packages on melpa (shm and ghc-mod so far), I created a shared sandbox in .emacs.d, and symlink any executables to a emacs-specific directory on the path.

I'm hoping to then somehow find a way to automatically cabal re-install when packages upgrade.

**Comment by chrisdone** [comment]
I don't use MELPA or know how to contribute to it. My Emacs packages tend to just appear on these new trendy package sites and that's fine with me. :-)

**Comment by tonyday567** [comment]
That's very funny!  I did see from your dot repo you're hard-core old-school.

I'll see if I can track down the melpa elves.
