### ISSUE TITLE
hindent substitutes unicode characters with escape codes

### ISSUE THREAD

**Issue by lunaryorn** [chrisdone/hindent#66]
On my system, `hindent` substitutes unicode characters with escape codes:

```console
$ hindent --style fundamental <<EOF                                                                                                 git:global-mode-without-checker
heredoc> foo = "…"
heredoc> EOF
foo = 
  "\8230"
```

Is that intentional?

**Comment by chrisdone** [comment]
No, it's an artifact of parsing into a string.

**Comment by lunaryorn** [comment]
@chrisdone I presume, it's an issue in haskell-src-exts then, and can't be fixed in hindent, can it?

**Comment by chrisdone** [comment]
I think it's inherent to the way HSE represents a string.

**Comment by lunaryorn** [comment]
@chrisdone Ah, ok.  Do you think that it's a good idea to work around this on the Emacs side, by back-substituting unicode escapes with their character equivalent?  Probably via a new customization option?

**Comment by chrisdone** [comment]
I think it's possible for hindent to workaround it by using the source spans of the original string positions as a way to recover the original text of the string literal, producing a `Map SrcLoc [StringComponent]` where `data StringComponent = Plain String | Escaped String | Newline`. Then when pretty printing a string it can lookup from the map the real string and print that instead.

**Comment by chrisdone** [comment]
If you want to tackle it I'd change the printer [here](https://github.com/chrisdone/hindent/blob/master/src/HIndent/Pretty.hs#L1217..L1219) to be aware in this way, and a field to `NodeInfo` like `nodeInfoLiteral :: Maybe LiteralRep` and then similar to [`annotateComments`](https://github.com/chrisdone/hindent/blob/master/src/HIndent.hs#L112..L112) add an `annotateLiterals :: (Data (ast NodeInfo), Annotated ast) => String -> ast NodeInfo -> ast NodeInfo` which will detect strings, numbers, etc and put them in the `NodeInfo`. Later in the printer it can then look at the sum type `LiteralRep` and print the literal back as it was originally parsed. Maybe `LiteralRep` would be like:

``` haskell
data StringComponent = Plain String | Escaped String | Newline
data LiteralRep = CharRep String | StringRep [StringComponent] | NumericRep String | Unboxed LiteralRep
```

Then you'd have like:

``` haskell
instance Pretty Literal where
  prettyInternal l = 
    case nodeInfoLiteral (ann l) of
      Just rep ->
        case rep of
          StringRep cs -> do write "\""; mapM_ prettyComponent cs; write "\""
          …
      Nothing -> pretty' l
```

**Comment by chrisdone** [comment]
Alternatively we could maybe ask the HSE guys whether `Literal` could be a sum type of `Verbatim` versus `Translated` or whatever.

**Comment by alanz** [comment]
FYI GHC now keeps the original text of literals, to obviate this problem, and the current ghc-exactprint can roundtrip the source example above

**Comment by gibiansky** [comment]
I think this is not quite right. `haskell-src-ext` literals are stored in the following data type:

```haskell
data Literal l
    = Char       l Char     String     -- ^ character literal
    | String     l String   String     -- ^ string literal
    | Int        l Integer  String     -- ^ integer literal
    | Frac       l Rational String     -- ^ floating point literal
    | PrimInt    l Integer  String     -- ^ unboxed integer literal
    | PrimWord   l Integer  String     -- ^ unboxed word literal
    | PrimFloat  l Rational String     -- ^ unboxed float literal
    | PrimDouble l Rational String     -- ^ unboxed double literal
    | PrimChar   l Char     String     -- ^ unboxed character literal
    | PrimString l String   String     -- ^ unboxed string literal
```
The second element of each of those is the original source form of the literal. So we can literally just use that second field and print that out; this is just a bug in `haskell-src-ext`'s `prettyPrint`, I believe.

I've taken a shot at fixing this in the `respect-unicode-in-literals` branch if you'd like to take a look.

**Comment by gibiansky** [comment]
Specifically, [this commit](https://github.com/chrisdone/hindent/commit/e57a7f981df4965b0e729fb27ce802324c5a06c6) should fix the issue.

**Comment by chrisdone** [comment]
@gibiansky Yeah, that representation of Literal was added in HSE 1.16. In 1.15 it didn't have this retention of the original string.

**Comment by gibiansky** [comment]
@chrisdone I thought so too for some reason, but it's actually been there all along, surprisingly enough (http://hackage.haskell.org/package/haskell-src-exts-1.15.0.1/docs/Language-Haskell-Exts-Annotated-Syntax.html#t:Literal). That said it may have been incorrectly utilized prior to 1.16. Either way, doesn't really matter -- just wanted to make sure I wasn't missing anything, will merge this fix shortly.

**Comment by chrisdone** [comment]
Ahh, the annotated form differs to the non-annotated form because reasons.

**Comment by gibiansky** [comment]
Oh, wow, that's confusing. That's *still* the case in 1.16. Interesting, but ok.

**Comment by chrisdone** [comment]
![Oh well](http://p0wn3d.de/funstuff/dunno.gif)

Carry, sir.
