### ISSUE TITLE
Tibell style doesn't line break often enough

### ISSUE THREAD

**Issue by chrisdone** [chrisdone/hindent#67]
Things like this:
``` haskell
parsePackageIdent = fmap fst .
    listToMaybe .
    filter (null . snd) .
    readP_to_S parse . T.unpack
```

Ping @emmanueltouzery

**Comment by emmanueltouzery** [comment]
sure! I agree that the Tibell style is very raw. Not usable for me yet, definitely. We need to grow the test cases. I don't have the set-up on the computer right now to check what is the output for this, but I'll try to look at this case before the end of the week-end. Hopefully I can fix it and add the matching test case!

**Comment by emmanueltouzery** [comment]
hmm I was looking at it now. What you pasted is what the engine is generating. That is the output. I thought that is what you want, but it seems you want more line breaks than that?

It looks good to me. How do you think this should be indented for the Tibell style?

(confession: I have a strong trend to make very long lines myself)

**Comment by emmanueltouzery** [comment]
maybe you want the `fmap` not to be directly after the `=` but on the next line, the rest as-is?

**Comment by chrisdone** [comment]
I'd think it should be on the next line, yeah. For function application having the parent up there makes sense but less so for binary stuff where the operands are equally important.

**Comment by emmanueltouzery** [comment]
I think that commit of mine is to blame:
https://github.com/chrisdone/hindent/commit/81f68502ceaff49bb25c180da46669ff9910c8bc

I made a little change locally using `isFlat` on the RHS to decide whether we add a newline or not. It achieves the purpose, but breaks tests 1, 2 and 4 for the Tibell indentation style.

My trouble is that I'm not quite sure how it should behave correctly. Those tests were added by me.

Would it be correct to modify the expected for 1, 2 and 4 to add that CR? Is `isFlat` a good determination for the carriage return? Or we can consider reverting that commit.

**Comment by chrisdone** [comment]
I'm not a proponent of this style, nor do I particularly understand the heuristics of it, but I work with enough code in it to recognize these differences. It's an undeveloped style in hindent, I think you are its first proper user and contributor so the existing printer isn't perfect. @gibiansky started with it but ended up writing his own, and @ocharles started on it and switched to mine.

I think test 2 makes *some* sense (including for discussion purposes):

``` haskell
strToMonth :: String -> Int
strToMonth month = case month of
        "Jan" -> 1
        "Feb" -> 2
        _ -> error $ "Unknown month " ++ month
```

This kind of swinging of children "under the bridge" is definitely common in this style so that seems legit, although the line has been indented 8 spaces instead of only 4, so this doesn't quite meet [the style guide.](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md)

Test 1 doesn't go well with the style that @tibbe (pinging also @snoyberg @jwiegley @mgsloan if they want to chime in) prescribes:

``` haskell
getGitProvider :: EventProvider GitRecord ()
getGitProvider = EventProvider {getModuleName = "Git"
                               ,getEvents = getRepoCommits}
```

I think users of the tibbe style would argue that a child's column should never depend upon its parents column if that column is variable (`if`/`then` is okay because those never change). So if you rename `EventProvider` to `EventProv` then `getEvents` will have to be re-indented even though it is unchanged.

It's not an egregious difference so we don't have to revert it: rather, I'd appreciate some enhancements to the style if you have the time to contribute to it. :-) If not, I'll get round to fixing this because I've started using it on other people's codebases that I'm working on, but no telling when I'll get round to it.

**Comment by emmanueltouzery** [comment]
Yes, it's possible I'll pass up on this. I don't fully understand the subtleties of the requirements (as I said I currently have my own -bad- coding style which is different from all those) and without existing tests it makes things even harder. I'll be delighted if you can bring it up to speed, and hopefully I'll use ASAP (currently not using it yet). I'm glad to fix some issues but if you intend to start using it seriously, I think before it's up to speed you'd spend considerably more energy explaining the requirements to me (and in some cases internal tools already available in hindent) than coding it yourself...

**Comment by mgsloan** [comment]
I'd definitely indent the body of that case only 4, instead.  Personally, lately I've been gravitating towards not doing that sort of "broken indent" style for case / if / etc.

**Comment by tibbe** [comment]
> I think users of the tibbe style would argue that a child's column should never depend upon its parents column if that column is variable (if/then is okay because those never change). So if you rename EventProvider to EventProv then getEvents will have to be re-indented even though it is unchanged.

I think that's a pretty good argument, although it's not one I'm making in my style guide, which allows

```haskell
getGitProvider = EventProvider { getModuleName = "Git"
                               , getEvents = getRepoCommits
                               }
```

or

```haskell
getGitProvider = EventProvider
    { getModuleName = "Git"
    , getEvents = getRepoCommits
    }
```

or maybe

```haskell
getGitProvider = EventProvider {
      getModuleName = "Git"
    , getEvents = getRepoCommits
    }
```

I am in general a fan of the "swinging of children "under the bridge"" style where you do

```haskell
someLongerName withLong argument names = case ... of
    First ->
    Second ->
```

because, as you say, it makes the indentation much more consistent (i.e. it doesn't depend on the length of the functions names or argument names.)

**Comment by jwiegley** [comment]
I also have grown fond of the swinging under the bridge style.
