### ISSUE TITLE
Line length flag

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/hindent#69]
There should be a flag to set the desired max line length.

This was originally brought up in #26 but should have its own issue page so that it can be tracked separately.

**Comment by chrisdone** [comment]
How's that?

    chris@retina:~/Emacs/packages/hindent$ echo 'x = foo bar mu zot hello hello world what up homie world  homie' | hindent --style chris-done --line-length 60; echo
    x = 
      foo bar mu zot hello hello world what up homie world homie
    chris@retina:~/Emacs/packages/hindent$ echo 'x = foo bar mu zot hello hello world what up homie world  homie' | hindent --style chris-done --line-length 30; echo
    x = 
      foo bar
          mu
          zot
          hello
          hello
          world
          what
          up
          homie
          world
          homie

**Comment by gibiansky** [comment]
Awesome! 

Now I see what the `descriptive` package was being used for. I was wondering why that dependency appeared...
