### ISSUE TITLE
Gibiansky outputs incorrect code for long lists in do expressions

### ISSUE THREAD

**Issue by expipiplus1** [chrisdone/hindent#80]
```haskell
module Main where

foo = do bar [Shall, we, but, treason, and, indent, with, fears]
         baz [It, shall, not, wind, with, such, a, deep, indent, To, rob, me, off, so, rich, a, bottom, here]
```

The first list is short enough to go on one line and is formatted correctly, the second is split onto two lines and `baz` is somehow unindented to the top level

**Comment by gibiansky** [comment]
@expipiplus1 Make sure to tag me via `@gibiansky` on styles related to my printer. Thanks for the bug report, will take a look.
