### ISSUE TITLE
Support for recent versions of descriptive?

### ISSUE THREAD

**Issue by peti** [chrisdone/hindent#81]
Will there be a new version that can compile against the latest release of `descriptive`?

**Comment by chrisdone** [comment]
Sure, master does. I'll push to Hackage.

**Comment by chrisdone** [comment]
http://hackage.haskell.org/package/hindent-4.2.2

**Comment by peti** [comment]
Thanks a lot! We've picked up the latest version of `descriptive` in NixOS, but that broke the `hindent` build. The new version makes our lives easier, because now we won't have to worry about carrying multiple versions of `descriptive`.
