### ISSUE TITLE
hindent-4.2.3 fails its test suite (because of missing files?)

### ISSUE THREAD

**Issue by peti** [chrisdone/hindent#83]
Running 1 test suites...
    Test suite hspec: RUNNING...
    hspec: test/fundamental/tests/: getDirectoryContents: does not exist (No such file or directory)
    Test suite hspec: FAIL

The complete build log is at http://hydra.cryp.to/build/502501/nixlog/2/raw.

**Comment by gibiansky** [comment]
Is this still happening? It seems like all the files should be in the `data-files` field of `cabal`, and [Travis CI](https://travis-ci.org/chrisdone/hindent/builds) seems to be validating the build -- is this just an interaction between nix and `hindent` issue?

**Comment by chrisdone** [comment]
Seems to be working fine from Hackage.

**Comment by peti** [comment]
Yes, in ` hindent-4.4.1` the tests succeed fine.
