### ISSUE TITLE
User state?

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/hindent#84]
@chrisdone 

How do you update the user state? There are currently no styles that use anything except
```haskell
data State = State
```
for the user state. I have a use case (I think, need some experimentation) for a user-specific state. The extenders get that state as an argument, but it does not seem like there is a way to update it.

How should one deal with getting and updating the user state in an Extender? Since the `PrintState` existentially quantifies over `s`, there's no way to use `get` or `put` in the user style to modify `s`. (This seems like me misunderstanding the design somewhat...)

**Comment by chrisdone** [comment]
Oh, let me fix that.

**Comment by chrisdone** [comment]
This should do the trick. Use `putState`/`getState`/`modifyState` from Pretty.hs.
