### ISSUE TITLE
descriptive-0.3.0 can't compile its test suite

### ISSUE THREAD

**Issue by peti** [chrisdone/hindent#85]
Sorry for putting this report here, but the `descriptive` project doesn't seem to have an issue tracker? The new `descriptive` release cannot compile its test program: http://hydra.cryp.to/build/519913/nixlog/2/raw. This affects the build of `hindent`, naturally. :-)

**Comment by chrisdone** [comment]
Fixed the test suite of descriptive in 0.3.1.
