### ISSUE TITLE
descriptive-0.9.0 can't build its test suite

### ISSUE THREAD

**Issue by peti** [chrisdone/hindent#93]
I tried to build hindent, but failed because of the following build error in the `descriptive` dependency:

    In-place registering descriptive-0.9.0...
    Preprocessing test suite 'test' for descriptive-0.9.0...
    [1 of 1] Compiling Main             ( src/test/Main.hs, dist/build/test/test-tmp/Main.dyn_o )

    src/test/Main.hs:97:11: Not in scope: ‘validate’

A complete build log is here: http://hydra.cryp.to/build/577927/nixlog/1/raw.

P.S.: Is it intentional that descriptive has no issue tracker?

**Comment by chrisdone** [comment]
Fix in `0.9.1`.

> P.S.: Is it intentional that descriptive has no issue tracker?

Yes.

**Comment by peti** [comment]
So how am I supposed to report issues such as this one in the future? Adding it to the `hindent` issue tracker doesn't seem ideal, no? Is there a better way?

**Comment by peti** [comment]
The test suite for `descriptive-0.9.1` fails with the following errors:

    Test suite test: RUNNING...

    Descriptive.Char
      describe FAILED [1]
      consume
      fail generic
      fail specific
    Descriptive.Form
      basic describe login
      basic describe login
      succeeding login
      continuing login FAILED [2]
      succeeding disjunction
    Descriptive.Formlet
      basic formlet
      succeeding formlet
      succeeding formlet
    Descriptive.JSON
      describe JSON
      succeeding json
      failing json
    Descriptive.Options
      describe options FAILED [3]
      succeeding options
      succeeding omitting port options
      failing options

    Failures:

      1) Descriptive.Char describe

      2) Descriptive.Form continuing login

      3) Descriptive.Options describe options

    Randomized with seed 2014067795

A complete build log is at http://hydra.cryp.to/build/578322/nixlog/2/raw.

**Comment by chrisdone** [comment]
Disabled test suite in 0.9.2.
