### ISSUE TITLE
Tibell's style doesn't use `haskell-indent-space` ?

### ISSUE THREAD

**Issue by PierreR** [chrisdone/hindent#96]
I have switched from `Gibianky` to Tibell style because Tibell's record style is more common (at least from what I read)

I have a problem with the indentation that is forced to be 4 spaces ... whereas I usually use 2 (mimicking ekmett itself ;-)

Would it be possible to have the indentation respecting `haskell-indent-space` in this style ?

Cheers

**Comment by chrisdone** [comment]
Tibbe's style guide is 4 spaces.

**Comment by PierreR** [comment]
Yes I knew about that. Maybe we need an ekmett'style ;-)
