### ISSUE TITLE
Automatically reformat comments to be proper line length?

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/hindent#97]
Is this something we want to support? This would be a feature I would find very convenient but is perhaps out of scope of hindent. (If we do support this, IMHO it should be behind a flag.)

Sadly this has to be a global issue, because right now styles cannot change comments in more or less any way.

**Comment by chrisdone** [comment]
Sounds reasonable. As a flag that sounds good.

We could possibly support comments in styles themselves by having it call the extenders list, if desired.

**Comment by gibiansky** [comment]
Addressed in #108

**Comment by gibiansky** [comment]
Done.
