### ISSUE TITLE
Travis CI?

### ISSUE THREAD

**Issue by gibiansky** [chrisdone/hindent#99]
I recently set up Travis CI for IHaskell and it is pretty easy to set up and seems quite useful. Perhaps it might be worthwhile to set up for `hindent`, especially since we have a pretty comprehensive test suite?

**Comment by chrisdone** [comment]
Sure.

**Comment by gibiansky** [comment]
Great. Since it's your repo, you'll need to sign up for travis and enable it for `hindent`; I'm happy to push a `.travis.yml` for it if you want.

**Comment by chrisdone** [comment]
Enabled.

**Comment by gibiansky** [comment]
@chrisdone 

Travis is mostly set up; 7.10 and up do not work yet (unsurprisingly) due to many dependency issues, but it's probably too early to try to get that to work. As of the last commit 7.8.3 *should* be building and passing.

7.6.3 does not currently pass due to the following class:
```haskell
class (Annotated ast,Typeable ast) => Pretty ast where
  prettyInternal :: MonadState (PrintState s) m => ast NodeInfo -> m ()
```
which yields the following horribly uninformative error message
```
src/HIndent/Pretty.hs:88:31:
    Expecting one more argument to `ast'
    In the class declaration for `Pretty'
```
which I believe is actually a kind mismatch due to the fact that `base-4.6` expects you to use `Typeable1` instead of `Typeable` in this context. 

This question is up to you: do you want to support GHC 7.6.3 by adding in some CPP that uses `Typeable1` instead of `Typeable` for the `Pretty` typeclass (if that is indeed the issue, anyways...), or should `hindent` just support 7.8 and up?

Once that's decided I can either try my hand at fixing it up for 7.6.3 (that said, I don't have 7.6, so it would be using Travis as a testing tool), or remove the 7.6 check from travis. Once that's done I'll go ahead and add the fancy-schmancy Travis badge to the README, and we can start using Travis' feedback on PRs as a prerequisite for merging.

**Comment by chrisdone** [comment]
Right, at some point I decided I didn't want to bother adding CPP to support this. I'm okay with it only working on 7.8. If you feel like adding the CPP feel free, I don't mind maintaining that, it's a small thing anyway.

**Comment by gibiansky** [comment]
I don't use 7.6 and since there haven't been any requests for it on the issues list, I'm fine with it just being 7.8+; I've changed `hindent.cabal` to require `base >= 4.7` in order to accurately reflect that dependency. Travis should now work and things should build and pass tests, so closing this issue.
